"""create expenses table

Revision ID: 59f1427eccaf
Revises: debceef93796
Create Date: 2026-06-05 16:56:42.930754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f1427eccaf'
down_revision: Union[str, None] = 'debceef93796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_expenses_user_category', 'expenses', ['user_id', 'category_id'], unique=False)
    op.create_index('ix_expenses_user_date', 'expenses', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expenses_user_date', table_name='expenses')
    op.drop_index('ix_expenses_user_category', table_name='expenses')
    # ### end Alembic commands ###
